# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 12:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('is_admin', models.BooleanField(db_index=True, default=False)),
                ('message_count', models.IntegerField(default=0)),
                ('command_count', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=64, unique=True)),
                ('register_time', models.TimeField(auto_now=True, verbose_name='date registered')),
                ('invite_link', models.CharField(db_index=True, max_length=64, unique=True)),
                ('url', models.CharField(max_length=256, unique=True)),
                ('is_removed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(verbose_name='timestamp')),
                ('level', models.CharField(max_length=64)),
                ('type', models.CharField(max_length=64)),
                ('message', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dwarf.Guild')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=2048)),
                ('clean_content', models.TextField(max_length=2048)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dwarf.Channel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dwarf.Guild')),
            ],
        ),
        migrations.CreateModel(
            name='String',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('en_us', models.CharField(max_length=2048)),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dwarf.Guild'),
        ),
    ]
